### ISSUE TITLE
Issue with pagenumber in response on the `transfers` index endpoint

### ISSUE THREAD

**Issue by bilfeldt** [MobilePayDev/MobilePay-Payments-API#68]
There seems to be a bug on the `transfers` endpoint in situations of pagination where `nextPageNumber` is not equal to `pagenumber + 1` but instead equal to the sum of results + 1

## Example

- URL: `https://api.mobilepay.dk/v3/reporting/transfers?startdate=2021-09-01&pagenumber=1&pagesize=10`
- Response variables:
  - `pageSize=10`
  - `nextPageNumber=11` <!-- This should have been `2` since we requested `pagenumber=1` in the url

Note that when there is no pagination `nextPageNumber` is correctly set to `null`

**Comment by edvinasmuncelis** [comment]
@bilfeldt There's definitely a bug. Thanks again for reporting! 🥇  We'll fix it asap and I'll close this issue when the fix is in production.

**Comment by JonasGavenavicius** [comment]
Hi @bilfeldt, once again, thanks for reporting the bug and taking the time and effort to create and raise a pull request, that's awesome! Issues regarding `nextPageNumber` in `v3/reporting/transfers` and the sort direction bug which you specified in your PR was resolved! Thanks again for your input. :)

**Comment by bilfeldt** [comment]
> Hi @bilfeldt, once again, thanks for reporting the bug and taking the time and effort to create and raise a pull request, that's awesome!

You are welcome @JonasGavenavicius. Glad to see my feedback being used.

> Issues regarding `nextPageNumber` in `v3/reporting/transfers`

I can confirm this is now working 👍 

> the sort direction bug which you specified in your PR was resolved!

Both `v3/reporting/transfers` and `v3/reporting/transactions` now return the latest records first (top of page 1 will be the **latest**) and older records on the next pages.

Any chance this sorting could be configurable using some query parameter? This sorting is very unfortunate for systems trying to sync changes since the last sync as it requires all pages to be fetched and then the complete list reversed. Thanks.

**Comment by edvinasmuncelis** [comment]
Hi @bilfeldt . We've noted your feature request and we'll try get it prioritised and implemented as soon as possible.

**Comment by edvinasmuncelis** [comment]
Hey @bilfeldt. We've added sort direction as a query parameter. More info: https://mobilepaydev.github.io/MobilePay-Payments-API/docs/reporting/release-notes#2022-09-20

**Comment by bilfeldt** [comment]
> Hey @bilfeldt. We've added sort direction as a query parameter. More info: https://mobilepaydev.github.io/MobilePay-Payments-API/docs/reporting/release-notes#2022-09-20

Thanks. To be tested shortly then 👍
